exclude_patterns:
- "spec/"
- "**/vendor/"
- 'config/initializers/simple_form_bootstrap.rb'
- 'app/controllers/authentication/confirmations_controller.rb'
- 'app/assets/javascripts/js/'
- 'app/assets/javascripts/tinyMCE/'
- 'db'
plugins:
  reek:
    enabled: true # uses rules from .reek.yml
  rubcop:
    enabled: true # uses rules from .rubocop.yml
  brakeman:
    enabled: true
  flog:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  eslint:
    enabled: true
  haml-lint:
    enabled: true
  scss-lint:
    enabled: true
  sass-lint:
    enabled: true
